
import { Inter } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import Headerr from "@/components/header";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Suspense fallback={<loading />}>{children}</Suspense></body>
    </html>
  );
}
